# Generated by Django 2.0.5 on 2018-10-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0003_reservations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='user_id',
            new_name='user',
        ),
    ]
