# Generated by Django 2.0.5 on 2018-10-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0006_auto_20181004_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='reservation_id',
            new_name='reservation',
        ),
    ]
