# Generated by Django 2.0.5 on 2018-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0008_auto_20181004_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation',
            field=models.SlugField(max_length=6),
        ),
    ]
