# Generated by Django 2.0.5 on 2018-10-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0009_auto_20181004_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='reservation',
        ),
    ]
