# Generated by Django 2.0.5 on 2018-10-04 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0010_remove_reservations_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='arrival',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='departure',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='instructor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='meal',
            field=models.BooleanField(default=False),
        ),
    ]
