# Generated by Django 2.0.5 on 2018-10-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0013_auto_20181004_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='instructor',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='meal',
            field=models.NullBooleanField(default=False),
        ),
    ]
