# Generated by Django 2.0.5 on 2018-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0014_auto_20181004_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Zaawansowany'), ('2', 'Średniozaawansowany'), ('3', 'Początkujący')], max_length=1)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Cela'), ('2', 'Komnata ze współbratem'), ('3', 'Klasyczna trójka z łazienką'), ('4', 'Dormitorium')], max_length=1)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('avalamount', models.IntegerField()),
                ('available', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='adult',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservations',
            name='child',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
