# Generated by Django 2.0.5 on 2018-10-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0016_auto_20181005_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='room',
        ),
    ]
