# Generated by Django 2.0.5 on 2018-10-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0017_remove_reservations_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='domskis.Rooms'),
            preserve_default=False,
        ),
    ]
