# Generated by Django 2.0.5 on 2019-04-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0018_reservations_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationsInstructors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_user', models.CharField(max_length=200, null=True)),
                ('adult', models.IntegerField(null=True)),
                ('child', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='child',
        ),
        migrations.AlterField(
            model_name='instructors',
            name='type',
            field=models.CharField(choices=[('1', 'Początkujący'), ('2', 'Średniozaawansowany'), ('3', 'Zaawansowany')], max_length=1),
        ),
        migrations.AddField(
            model_name='reservationsinstructors',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domskis.Instructors'),
        ),
        migrations.AddField(
            model_name='reservationsinstructors',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domskis.Reservations'),
        ),
    ]
