# Generated by Django 2.0.5 on 2019-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0021_auto_20190407_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='text',
            new_name='additional_information',
        ),
        migrations.AddField(
            model_name='reservations',
            name='instructors',
            field=models.ManyToManyField(through='domskis.CourseDetails', to='domskis.Instructors'),
        ),
    ]
