# Generated by Django 2.0.5 on 2019-04-12 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domskis', '0022_auto_20190410_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domskis.Instructors'),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
